### ISSUE TITLE
[REWRITE] Design

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#149]
Should ultimately look similar to this https://www.archlinux.org/ / https://aur.archlinux.org/

Very simple and clean.

**Comment by ferventcoder** [comment]
Note the packages page probably shouldn't look quite like that but you get the gist.

**Comment by gep13** [comment]
Have you thought about what it will be written in?

**Comment by ferventcoder** [comment]
ASP.NET MVC - What version is unknown.

**Comment by gep13** [comment]
Cool, look forward to helping out with it.

**Comment by robertbaker** [comment]
Found it. Sorry about that. I was looking at this repo, meant to put it here.

I read most of the other issues on this. Looks like you are too busy with other tasks than the site, which is why I would like to spearhead this project.

---
In 2006 before nuget was a thing, I started my own install/updater for Windows called Seven Update (before Windows 7). When the win store was announced for 8, I thought things would change. I also found choco sometime after that and made the decision to stop.

I'm now full stack, I have the experience needed for this web project and the CLI. I want to focus on the site first, make it easy to learn about choco and install. Focus on package management experience. Extend the apis to CI runners to publish packages (if that isn't already possible).

I also want to help solving the verification, moderation aspect. In order for choco to be adopted by the app maintainers, need to lower the barrier and reduce resistance. If a trusted system like was used, this would lower the need for moderation.

I don't agree with making it look like arch Linux or keeping it Razor. 

I briefly looked over the code so I apologize if I mention something already done.


I propose the following:

* Update core infrastructure to latest nugets and Technologies.

* Use Identity and enabling js web tokens. (this will help with oauth and 2factor).

* Convert to asp.net core and DNX

* Replace Razor with Angular2, typescript, and webpack.

* Use gulp to package front end.

* Update controllers to api calls as needed.

* update api to support caching.

* Use Angular-Material (would have to be ng1, currently).

* Fresh inviting design with influences of material.

* mobile friendly, responsive.

**Comment by ferventcoder** [comment]
Hi @robertbaker - I hear a much bigger conversation in here. I think maybe there are some things here that may require a more at length conversation (read: perhaps a video call) to share where Chocolatey is going and talk through some of your ideas and see how those fit into the goals. Send me an email directly at ferventcoder at gmail. Thanks!

**Comment by designxsteph** [comment]
The redesign of the front-end of the website has been launched in September 2019.
