### ISSUE TITLE
Pin IEX install to 0.9.8.33 for automation purposes (TEMPORARY)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#162]

**Comment by alexchandel** [comment]
1 month later, time to update? Any automation tools that haven't been updated deserve to be broken. Above all else, because `https://chocolatey.org/install.ps1` is installation method for *humans*. It's on the homepage. It needs to be updated. Continually sending new users to an old version of chocolatey will only cause more issues in the long run.

**Comment by ferventcoder** [comment]
Yep, planned to do that today already.

**Comment by alexchandel** [comment]
Lol, great minds.
