### ISSUE TITLE
Show user names in Disqus mails

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey.org#366]
### What You Are Seeing?
When an email is sent to the maintainer about a Disqus comment, I can not see who posted it.
### What is Expected?
The user name of the user who posted

**Comment by ferventcoder** [comment]
Thanks!

**Comment by gep13** [comment]
@aronovgj @ferventcoder yeah, I am not sure if this is possible :cry: 

If I remember correctly, the information that is sent from Disqus does not include the logged in user name.  **NOTE:** this might have changed since I last looked into it.  If the user is _also_ logged into chocolatey.org, we could use their username from there, but I think at the time we decided to go with consistency, and simply not include that information.

**Comment by ferventcoder** [comment]
I was afraid of that.

**Comment by gep13** [comment]
@ferventcoder I can do some digging, to see if things have changed.

**Comment by gep13** [comment]
@ferventcoder @aronovgj it doesn't look like anything has changed in this regard:

https://help.disqus.com/customer/portal/articles/466258-capturing-disqus-commenting-activity-via-callbacks

There is a very limited set of information available :cry:

**Comment by ferventcoder** [comment]
Right now it doesn't appear we can do this. So closing for now.
