### ISSUE TITLE
User appears not logged in due to heavy caching

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#382]
When you go to select pages (the main page, the about page, the first packages page), it will log in instead of your user name. It should show your user name.

**Comment by RickStrahl** [comment]
I see this too, and it's really quite bad.

I've logged out killed all my cookies for the site started a new browser instance and came back to the site and it still shows me as logged in which is really messed up.

Also I've not been able to upload a new package due to this. I get to the upload page and then final acceptance fails. Yet I got an email notice, but when I go back to my account the new package isn't there.

Whatever you're doing with Caching it's not working :-)

FWIW, I had similar issues about a half a year ago and I thought it was a cookie problem, but now that I see this again it's pretty clear that something more serious is going on. At this point the admin interface is unusable to me. I can't get a new package uploaded.

**Comment by ferventcoder** [comment]
> I've logged out killed all my cookies for the site started a new browser instance and came back to the site and it still shows me as logged in which is really messed up. If I click on the logout button, repeatedly even, it still shows me logged in. But when I click on my account it pushes me back to the login page.

This is not a known issue and seems like a serious concern. I am having trouble reproducing this behavior.

**Comment by ferventcoder** [comment]
I'd love to get more details surrounding the unable to log out so I can try to reproduce it.

**Comment by ferventcoder** [comment]
> Whatever you're doing with Caching it's not working :-)

For the most part it is. The site is still functional even with what works out to 100+ requests per second (over 9 million requests per day). Hopefully we can resolve any wonkiness that you are seeing so that things continue to work well for you.

What you may have seen last year was a different state of the union. It's what necessitated the need for caching in the first place. We've added hardware and other infrastructure since then as well and will continue to grow the infrastructure as the site continues to grow in popularity.

**Comment by RickStrahl** [comment]
It's totally reproducable for me. It even happens across browsers. I don't think I've ever logged into Chocolatey with FireFox but even FF shows my login.

So for me the steps are:

* clear cookies for chocolatey.org 
* shut down browser
* Go to site (I see rstrahl as login)
* I click logout (rstrahl stays)
* I click on my account (sent to logon page)

I'm attaching a fiddler trace from Chrome (main browser) in case that may help.
[ChocolateyLogon.txt](https://github.com/chocolatey/chocolatey.org/files/265380/ChocolateyLogon.txt)

**Comment by RickStrahl** [comment]
If you want to trouble shoot you're welcome to take a look at my machine. DM me on Twitter.

**Comment by ferventcoder** [comment]
> Caching is nice when it works but a disaster if it doesn't. it seems there should be no caching of logged in content ever (other than perhaps the downloads).

I'm pretty sure I might have figured out how to make this happen. You are probably lucky enough to be hitting a different edge cache where when you hit one of the heavily cached pages you are the only one logged in at the time. Then when you log out, those pages are still cached with your user name - the fix I'm working on would cover this scenario as well.

I can assure that there is no caching of internal pages, and the pages where you see it appear as if you are logged in or not logged in depending on the cache, those are the home page, about, and the first page of the packages page. The other pages are not cached in the same way.

**Comment by RickStrahl** [comment]
I tried again just now and I still see the same behavior. In addition:

* Visit home page - shows Log In option
* I sign in
* Redirect back to home page - Log In still shows
* Click on Log In again - Infinite Redirect and Chrome Crashes

Now if I go back to the site and browse around I see some pages show my login info while others do not. Not sure if that's old cached data or what, but it's freaky. If I click any of the LogIn links I get the infinite redirects while the user name link lets me get in. Poking around About and Upload show my name, Home and Packages shows LogIn.

Hope this helps...

**Comment by ferventcoder** [comment]
That's this issue, yes 👍 .

Why don't I remove the heavy caching on those pages until I have a solution ready? Let's do that and see if it resolves the other issue where you appear logged in when you are not.

**Comment by ferventcoder** [comment]
Done, I toned down the caching level a bit on those pages. For reference, these were the pages affected by this issue:

 * https://chocolatey.org
 * https://chocolatey.org/packages
 * https://chocolatey.org/about
 * https://chocolatey.org/packages?q=&moderatorQueue=&prerelease=true&sortOrder=package-download-count
 * https://chocolatey.org/packages?q=&moderatorQueue=&prerelease=false&sortOrder=package-download-count

Prior to the change I just made, if you were to go to these pages, they would appear as if you were not logged in. Or possibly in some cases, they may show your username erroneously when you were not logged in (which is a much bigger issue).

Now all should be good. As long as the site does not degrade in performance, I think we can leave it this way.

**Comment by ferventcoder** [comment]
Since this is no longer an issue, I'm going to close this one for now.

**Comment by ferventcoder** [comment]
@RickStrahl Let me know if you are still seeing this and we can investigate further.

**Comment by RickStrahl** [comment]
Yup that fixed it. The caching username issue is gone and the login redirect as well. Seems everything is working as it should.

Thanks!

As to the caching, I think the only thing that probably really benefits from caching are the packages pages and maybe you can partially cache the body rather than than the entire page.

Anyway appreciate you looking into this and making it work. Surprised that there haven't been other reports of this though because I've seen and brought it up this behavior months ago in a gitter chat.

**Comment by ferventcoder** [comment]
We only really started heavily caching about two weeks ago.

**Comment by RickStrahl** [comment]
Hmmmm... must have been something else but I was running into those same endless redirect issues before for sure. Anyway, it's working for now.

**Comment by ferventcoder** [comment]
We attempted it for about a minute a few months ago but backed it off really quickly when there were issues. This was a different way of going about it.

**Comment by ferventcoder** [comment]
Apologies you were running into the issue, but thanks for working with me to get it resolved! 👍

**Comment by RickStrahl** [comment]
No problem. I appreciate all the work you and your team are putting into Chocolatey. I rely on it for most of my new machine installs and many software updates as well as pushing out some of my tools to customers, so I'm grateful to see that it's here. 

I'm still surprised that Microsoft is not taking a more active role in this either as a supporter, by pushing package deployment in general (OneGet) or even by having something else, since a package store like this seems  to me these days is one of the most important pieces of the OS eco-system.

Anyway, thanks for all your hard work. Aloha!
