### ISSUE TITLE
Some pages aren't reliably loading

### ISSUE THREAD

**Issue by mjwills** [chocolatey/chocolatey.org#397]
### What You Are Seeing?
Loading this url fails roughly 30% of the time 
https://chocolatey.org/packages/microsoft-build-tools (when it fails it redirects to https://chocolatey.org/Errors/error.html?aspxerrorpath=/packages/microsoft-build-tools)

### What is Expected?
It to load more reliably :smiley: 

### How Did You Get This To Happen? (Steps to Reproduce)
I loaded https://chocolatey.org/packages/microsoft-build-tools in multiple tabs (and refreshed in single tab) and saw the behaviour

**Comment by mjwills** [comment]
This is occurring on Windows 10, across all browsers (Edge, Firefox, IE, Chrome)

**Comment by AFulgens** [comment]
For me not only that, but also the package repo seems to be down (I'm basically unable to install anything :))

**Comment by ferventcoder** [comment]
@mjwills @AFulgens all weekend we've been experiencing issues with one of the servers in our load balancer. I've taken it completely out just about 10 minutes ago. We'll see how the site performs today.

**Comment by mjwills** [comment]
Awesome, thanks.

**Comment by Wand3rvogel** [comment]
The problem persist.

**Comment by riezebosch** [comment]
The same problem occurs with choco install packages. Sometimes after the 3rd or 4th try it finally succeeds to download the package and installation just goes fine.

**Comment by ferventcoder** [comment]
More configuration changes. I've been in contact with our hosting service and have removed the necessity to have database access during the website startup (which the servers in the load balancer hit from time to time). 

Since the package information comes from an index and the download stats are shipped off to another service, there should be no increased pressure to the database at all now. We are keeping an eye on whether this resolves the issue. Please comment if you continue to see degraded service.

**Comment by ferventcoder** [comment]
Folks, if you are still seeing this, can you verify the user you are running this with is **not** SYSTEM.

**Comment by ferventcoder** [comment]
If it is local SYSTEM, we think we know why this is occurring and are going to fix it in 0.9.10.3.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/826

**Comment by ferventcoder** [comment]
This should now be resolved.
