### ISSUE TITLE
Install of a local package (.nupkg) do not honor version dependencies

### ISSUE THREAD

**Issue by fdcastel** [chocolatey/chocolatey.org#430]
### What You Are Seeing?

Dependencies are not honored when installing local packages (.nupkg file).

### What is Expected?

Package `firebird 2.5.6` has a dependency for `firebirdclient 2.5.6` in the .nuspec file.

A `choco install .\firebird.2.5.6.nupkg -y` should install the local package `.\firebirdclient.2.5.6.nupkg` as its dependency.

Instead, it installs the latest `firebirdclient` from chocolatey.org (`3.0.0.1`, currently).

### How Did You Get This To Happen? (Steps to Reproduce)

_(Chocolatey 0.10.0 running on Windows 10-1607)_

Put `firebird.2.5.6.nupkg` and `firebirdclient.2.5.6.nupkg` in current folder.

Run `choco install .\firebird.2.5.6.nupkg -y`

### Workaround

Run `choco install` passing the explicit version. E.g. `choco install .\firebird.2.5.6.nupkg -y  --version 2.5.6`.

This works. I don't know if this is the expected behavior, but I believe the automated tests for `firebird 2.5.6` package are failing because of this fact.

**Comment by ferventcoder** [comment]
Please submit full log output as gists - the one missing link for you is that when you call a local file like that, the source is set to the folder.

Really, running installs directly from the nupkg file is something that is limited to testing and we recommend 

`choco install firebird -s .` to get to the local file instead of running with nupkg are there are some known issues with the latter. The former should work without issue.

Also while you are prepping the gists for the logs, grab the latest version of choco. Run `choco new test` and then look at the nuspec that it produces to know if you are setting an exact version dependency or a minimum dependency.

`version="[2.5.6]"` (exact)
`version="2.5.6"` (minimum version dependency)

**Comment by ferventcoder** [comment]
Looks like some of this may just be education 

![image](https://cloud.githubusercontent.com/assets/63502/18688946/2f2d3826-7f4c-11e6-9c26-6835c7a44e71.png)

It's a big reason why we recommend running `choco new` every once in awhile, it provides quite a bit of just in time documentation, when you need it. We understand there is a bit of a gap here though when it comes to already existing packages.

**Comment by fdcastel** [comment]
> version="[2.5.6]" (exact)

Oops. My fault. Thank you. I didn't know this one.

I updated the nuspec with `version="[2.5.6]"` and the problem remained when installing directly via `.nupkg` file (but ok, you said there are some problems with it). 

However, using the `-s` it worked!

`choco install firebird -s . -y`

So, I presume this is the way the automated environment uses to check it. I'll resubmit the packages with the correct (exact) dependencies.



> It's a big reason why we recommend running choco new every once in awhile.

Understood. I will run one now and recheck all my templates. 

Thank you very much, Rob! Specially for the very instructive image above 😅

**Comment by ferventcoder** [comment]
No worries, glad to get you moving again. 👍
