### ISSUE TITLE
Error on uploading package from website

### ISSUE THREAD

**Issue by nicolafarina** [chocolatey/chocolatey.org#534]
Hi all,

I'm trying to upload a new package from the website (account area) but it seems that system is broken as I get the error page.

Anyway, a e-mail said me that package is under review so I don't know If it has reach the repository.

**Comment by gep13** [comment]
@nicolafarina what was the id of the package that you submitted?

**Comment by nicolafarina** [comment]
Sorry, forgot to mention "qap".

Probably you see more tentatives, please feel free to delete the duplicates.

**Comment by gep13** [comment]
Looks like your package is in the automatic moderation queue:

https://chocolatey.org/packages/qap

So, that part is fine. The issue with the error message, I think is a known issue, but @ferventcoder might be able to confirm that.

**Comment by nicolafarina** [comment]
@gep13 May I ask you why is switch "--version 8.5.3" present in the quick installation guide on the page? I haven't see any in other packages. 

Sorry for asking but is my first push.

**Comment by gep13** [comment]
@nicolafarina I think that this was covered in Gitter, but let me re-iterate here...

While your package version is in moderation, running the normal `choco install qap` won't work, as there isn't actually a package version that will resolve with that command.  However, in order to allow for testing the package (if required) you can use the command `choco install qap --version 8.5.3`.  This is not "recommended" since the package version not being approved means that it is still subject to change, and should be used sparingly.

Hope that helps!

**Comment by nicolafarina** [comment]
@gep13 Crystal clear. 

Many thanks.

**Comment by bcc** [comment]
+1, I'm getting the following uploading an update for UrlRewrite:

    Sorry, an error occurred while processing your request.
    Error: Oh no, we broke something!

I have got the moderation review email, so I'll wait and see what happens. There's nothing relevant on the package page yet though.

**Comment by bcc** [comment]
Nothing appeared despite the email. I've resubmitted the package this morning and it does seem to have succeeded.

**Comment by ferventcoder** [comment]
Superseded by #798.
