### ISSUE TITLE
Unify cygwin DLL's

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey.org#536]
Several Chocolatey packages include their own cygwin1.dll, which presents problems when conflicting versions are available on the PATH. Could Chocolatey offer a unified, up to date cygwin1.dll, and encourage the individual packages to omit this DLL, to avoid conflict?

**Comment by ferventcoder** [comment]
Hi @mcandre,
 The reason we encourage folks to use the shims is that it would avoid this issue and allow each app, which is compatible with each certain version of a DLL, to be on the path without putting those DLLS also on the path. 

Now that said, do keep in mind this is a binary package manager, which stops dependencies at the level of apps, not down to the DLLs. This is also a request for the community at large.

It would be easier for someone in the know (such as yourself) to seek out each maintainer and ask them what can be done to ensure that the Cygwin dlls are not on the path. 

I stress that having one cygwin dll package is the ***wrong*** answer, because each has a reason (typically compat) that they have a differing version. So they would each be installing a different version of that dll, and not solving the issue that you are seeing at all. Possibly making it worse. 

Does this make sense?

**Comment by ferventcoder** [comment]
@mcandre closing this due to nonresponse and it doesn't really apply.
