### ISSUE TITLE
Central Management - Please Update Documentation to Include LDAP feature

### ISSUE THREAD

**Issue by Chirishman** [chocolatey/chocolatey.org#846]
Please enhance the [Central Management documentation](https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Documentation/Files/FeaturesChocolateyCentralManagement.md) to include an explanation of the LDAP support [mentioned in the release notes](https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Documentation/Files/ReleaseNotesCentralManagement.md)

**Comment by gep13** [comment]
@Chirishman thank you for raising this issue.  We don't need two tickets to track the same thing, so I would suggest that we stick with the one in the licensed issues repository.  As such, I am going to go ahead and close this one out.

**Comment by ferventcoder** [comment]
@gep13 the actual work for this would be in the wiki docs, so we would want the ticket to be there. Since it is not internal, one could keep from having two tickets, but whichever ticket is being used should be located with the repository where the work is going to be done (so likely the ticket in licensed choco issues needs to be moved to choco wiki).  

IMHO I'd prefer to keep the one in the licensed repo and have a secondary ticket where the work will be completed as we would have one place to point customers to and it would ease support queries and searches (potentially not duplicating the request later). Thoughts?
