### ISSUE TITLE
Allow to uninstall chocolatey with a single command

### ISSUE THREAD

**Issue by evandrocoan** [chocolatey/chocolatey.org#849]
I can install chocolatey with this single powershell command:
`
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
`

But I cannot uninstall it because the uninstallation page does not have a single link to the uninstallation script. It asks the user to copy paste some script and create a file by himshelf: https://chocolatey.org/docs/uninstallation

**Comment by ferventcoder** [comment]
Hi @evandrocoan - we do provide a script for uninstallation. That satisfies the need. 

I don't think we will approach this aspect because it could have unintended side effects that folks may not have considered. So we need to have folks take a pause and consider before running that script. Also you could simply copy the text and paste it directly into a PowerShell session, no need to create a script first.
