### ISSUE TITLE
package vmrc ne s'installe plus cause mise a jour de la version

### ISSUE THREAD

**Issue by SUPRVISOR** [chocolatey/chocolatey.org#911]
Bonjour

comment fait-on pour mettre a jour un paquet car la version n'existe plus 

Attempt to get headers for https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.1.0/15913118/windows/vmrc-windows.tar failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.1.0/15913118/windows/vmrc-windows.tar'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading vmrc
  from 'https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.1.0/15913118/windows/vmrc-windows.tar'

La version est remplacer la 11.2.0-16492666
le lien a changer est : https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.2.0/16492666/windows/vmrc-windows.tar

**Comment by ferventcoder** [comment]
Google Translate: 


Hello

how do you update a package because the version no longer exists

Attempt to get headers for https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.1.0/15913118/windows/vmrc-windows.tar failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.1.0/15913118/windows/vmrc-windows.tar' . Exception calling "GetResponse" with "0" argument (s): "The remote server returned an error: (404) Not Found."
Downloading vmrc
from 'https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.1.0/15913118/windows/vmrc-windows.tar'

The version is replace 11.2.0-16492666
the link to change is: https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/11.2.0/16492666/windows/vmrc-windows.tar

**Comment by ferventcoder** [comment]
The package would need to be updated by the maintainer. HTH
