### ISSUE TITLE
Please reopen issue #765 - It Is Still Happening

### ISSUE THREAD

**Issue by DawnThomas** [chocolatey/chocolatey.org#914]
Installing dotnetcore with no version works fine.  However, if you reference a version and it is NOT the current version, it fails.

dotnetcore not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime (= 3.1.5)'.
dotnetcore package files install completed. Performing other installation steps.
The install of dotnetcore was NOT successful.
dotnetcore not installed. An error occurred during installation:
 Unable to resolve dependency 'dotnetcore-runtime (= 3.1.5)'.

**Comment by ferventcoder** [comment]
Related to #765

**Comment by ferventcoder** [comment]
While the aspects are the same from the consumer end, what is likely being experienced here is a caching issue. What was in #765 was a catastrophic failure related to changes that were being made. As such I've updated the title for that ticket. 


This isn't even a bug - this is because there is not an approved version of dotnetcore-runtime exact version 3.1.5 - it failed moderation. https://chocolatey.org/packages/dotnetcore-runtime/3.1.5 
You should reach out to the package maintainers.

**Comment by ferventcoder** [comment]
@DawnThomas I've updated this title as well and I've went in and made those package versions available. There was a change in one of the dependencies that the runtime needs that added quite a few required KB (hotfixes), one of which requires a reboot when applied.

**Comment by DawnThomas** [comment]
@ferventcoder Thank you so much for the explanation and the updates!
